---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/user/post/comments":
    get:
      summary: List of comments for a particular user
      tags:
      - Comments
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
      - name: params
        in: body
        schema:
          type: object
          properties:
            author_id:
              type: integer
            post_id:
              type: integer
          required:
          - author_id
          - post_id
      security:
      - JWT: {}
      responses:
        '200':
          description: Comments list
        '404':
          description: post not found
  "/api/v1/user/post/new_comment":
    post:
      summary: user comment on a particular post, ensure to add token as Authorization
        header
      tags:
      - Post Comment
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
      - name: params
        in: body
        schema:
          type: object
          properties:
            text:
              type: string
            post_id:
              type: integer
          required:
          - post_id
          - text
      security:
      - JWT: {}
      responses:
        '200':
          description: Post user comment, ensure to add token as Authorization header
        '404':
          description: post not found
  "/api/v1/users/login":
    post:
      summary: Authentication to get jwt token
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: Login Successful
        '401':
          description: Unauthorized
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
securityDefinitions:
  JWT:
    description: the jwt for API auth
    type: apiKey
    name: Authorization
    in: header
