default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin

development:
  <<: *default
  database: RwaBlogs_development

test:
  <<: *default
  database: RwaBlogs_test
  
production:
  <<: *default
  database: RwaBlogs_production
  username: postgres
  password: admin
